spring.application.name=demo
server.port=8081

# Logowanie
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.file.name=/var/log/lupus/lupusLogi.log

# Baza danych
#spring.datasource.url=jdbc:postgresql://psql01.mikr.us:5432/db_cezary161
#spring.datasource.username=cezary161
#spring.datasource.password=081B_751fcf
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=${JPA_SHOW_SQL:true}
#spring.jpa.properties.hibernate.format_sql=true
#hibernate.jdbc.lob.non_contextual_creation=true
##spring.jpa.hibernate.ddl-auto=update

# Baza danych test
spring.datasource.url=jdbc:postgresql://192.168.18.204:5433/lupusHRM
spring.datasource.username=lupusAdmin
spring.datasource.password=tofik123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
#spring.jpa.properties.hibernate.format_sql=true
#hibernate.jdbc.lob.non_contextual_creation=true

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Format daty
spring.mvc.format.date=yyyy-MM-dd


# Ustawienia uploadu plików
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# RUSTFS
rustfs.endpoint=http://localhost:9000
rustfs.access-key=lupusAdmin
rustfs.secret-key=bardzo_mocny_secret_key
rustfs.bucket=lupus-photos
rustfs.region=us-east-1

# JWT propetiesy
jwt.secret=ad1028hjd972h4gv3ojh5gb0[h34ge[rhv[385gn3oiu5nvu3h5rgh345g9[385hgr8h35rg== 
jwt.expiration=86400000

#JSESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=120m